FROM alpine
MAINTAINER <euank>

RUN apk update; apk add git; apk add gcc; apk add make; apk add musl-dev
RUN git clone https://github.com/klange/nyancat

WORKDIR /nyancat
RUN LDFLAGS="-static" CFLAGS="-Os" make

VOLUME ["/out"]
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
